"""Stable public Python API for :mod:`docket`.

Only names listed in :data:`docket.__all__` are public and covered by the
project's compatibility policy. Other modules, names, and implementation
details are internal unless the documentation explicitly says otherwise.
"""

__version__ = "0.4.0"

from .export import (
    ExportError,
    ExportOptions,
    ExportResult,
    export_document,
    get_exporter,
    list_exporters,
    register_exporter,
    export_to_facturae_xml,
)
from .matching import (
    match_invoice_to_po,
    match_invoices_to_contract,
    match_receipt_to_transactions,
    match_three_way,
)
from .catalog import (
    Address,
    BankAccount,
    BankStatement,
    Citation,
    CitedDocument,
    Contract,
    CreditNote,
    DocumentReference,
    Invoice,
    LineItem,
    Money,
    Party,
    PurchaseOrder,
    Receipt,
    SchemaError,
    SchemaInfo,
    SchemaSpec,
    TaxIdentifier,
    ValidationContext,
    Waybill,
    add_validator,
    get_schema,
    keywords,
    list_schemas,
    load_schema,
    migrate,
    register_schema,
    unregister_schema,
)
from .layout import (
    BoundingBox,
    DocumentLayout,
    PageLayout,
    Table,
    TableCell,
    TextLine,
    WordToken,
)
from .ocr import (
    BackendUnavailable,
    Capabilities,
    OcrBackend,
    OcrSettings,
    get_ocr_backend,
    list_ocr_backends,
    register_ocr_backend,
)
from .batch import BatchError, BatchMetrics, BatchOptions, BatchResult, process_batch
from .einvoice import (
    EInvoiceResourcesMissing,
    EInvoiceUnavailable,
    EInvoiceValidationOptions,
    EInvoiceValidationResult,
    FacturXPdfUnavailable,
    FacturXRoundTripResult,
    PdfAValidationIssue,
    PdfAValidationResult,
    extract_facturx_xml,
    fetch_einvoice_resources,
    generate_facturx_pdf,
    validate_pdfa,
    validate_einvoice,
    verify_facturx_round_trip,
)
from .einvoice import Profile as EInvoiceProfile
from .errors import ConfigurationError
from .options import OcrOptions, ProcessOptions, ReviewOptions
from .pipeline import process_document
from .verification import verify
from .corroboration import corroborate
from .pii import PiiCategory, PiiField, pii_fields
from .result import (
    DocumentError,
    DocumentResult,
    DocumentStatus,
    ProcessingMetrics,
    SourceLocation,
)
from .schemas import (
    BankTransaction,
    ClassificationResult,
    Discrepancy,
    DiscrepancyType,
    MatchingStatus,
    MatchResult,
    ValidationIssue,
)
from .templates import (
    FieldRule,
    ItemsRule,
    VendorTemplate,
    get_vendor_template,
    list_vendor_templates,
    register_vendor_template,
    unregister_vendor_template,
)

__all__ = [
    "__version__",
    "EInvoiceProfile",
    "EInvoiceResourcesMissing",
    "EInvoiceUnavailable",
    "EInvoiceValidationOptions",
    "EInvoiceValidationResult",
    "FacturXPdfUnavailable",
    "FacturXRoundTripResult",
    "PdfAValidationIssue",
    "PdfAValidationResult",
    "extract_facturx_xml",
    "fetch_einvoice_resources",
    "generate_facturx_pdf",
    "validate_pdfa",
    "validate_einvoice",
    "verify_facturx_round_trip",
    "BatchError",
    "BatchMetrics",
    "BatchOptions",
    "BatchResult",
    "process_batch",
    "add_validator",
    "Address",
    "BackendUnavailable",
    "BankAccount",
    "BankStatement",
    "BankTransaction",
    "BoundingBox",
    "Capabilities",
    "Citation",
    "CitedDocument",
    "ClassificationResult",
    "ConfigurationError",
    "Contract",
    "CreditNote",
    "Discrepancy",
    "DiscrepancyType",
    "DocumentError",
    "DocumentLayout",
    "DocumentReference",
    "DocumentResult",
    "DocumentStatus",
    "export_document",
    "export_to_facturae_xml",
    "ExportError",
    "ExportOptions",
    "ExportResult",
    "get_exporter",
    "get_ocr_backend",
    "get_schema",
    "Invoice",
    "keywords",
    "LineItem",
    "list_exporters",
    "list_ocr_backends",
    "list_schemas",
    "load_schema",
    "match_invoice_to_po",
    "match_invoices_to_contract",
    "match_receipt_to_transactions",
    "match_three_way",
    "MatchingStatus",
    "MatchResult",
    "migrate",
    "Money",
    "OcrBackend",
    "OcrOptions",
    "OcrSettings",
    "PageLayout",
    "Party",
    "process_document",
    "corroborate",
    "verify",
    "pii_fields",
    "PiiCategory",
    "PiiField",
    "ProcessingMetrics",
    "ProcessOptions",
    "PurchaseOrder",
    "Receipt",
    "register_exporter",
    "register_ocr_backend",
    "register_schema",
    "ReviewOptions",
    "SchemaError",
    "SchemaInfo",
    "SchemaSpec",
    "SourceLocation",
    "Table",
    "TableCell",
    "TaxIdentifier",
    "TextLine",
    "FieldRule",
    "ItemsRule",
    "VendorTemplate",
    "get_vendor_template",
    "list_vendor_templates",
    "register_vendor_template",
    "unregister_vendor_template",
    "unregister_schema",
    "ValidationContext",
    "ValidationIssue",
    "Waybill",
    "WordToken",
]
