"""The versioned schema catalog: built-in document types, custom ones, and the
shared models they are built from.

    from docket.catalog import get_schema, list_schemas

    spec = get_schema("invoice")          # latest version
    spec.version, spec.json_schema(), spec.exporters
"""
from .builtin import BUILTIN_SCHEMAS, register_builtins
from .common import (
    Address,
    BankAccount,
    Citation,
    CitedDocument,
    DocumentReference,
    LineItem,
    Money,
    Party,
    TaxIdentifier,
)
from .models import (
    BankStatement,
    BankStatementTransaction,
    Contract,
    CreditNote,
    Invoice,
    PurchaseOrder,
    Receipt,
    ReceiptItem,
    Waybill,
    WaybillItem,
)
from .registry import (
    ENTRY_POINT_GROUP,
    UNKNOWN,
    Keyword,
    Migration,
    SchemaError,
    SchemaInfo,
    SchemaSpec,
    ValidationContext,
    Validator,
    add_validator,
    adhoc,
    custom_schemas,
    for_model,
    get_schema,
    keywords,
    list_schemas,
    load_schema,
    migrate,
    parse_type,
    pattern,
    register_schema,
    require_schema,
    resolve,
    unregister_schema,
)

register_builtins()

__all__ = [
    "BUILTIN_SCHEMAS",
    "ENTRY_POINT_GROUP",
    "UNKNOWN",
    "Address",
    "BankAccount",
    "BankStatement",
    "BankStatementTransaction",
    "Citation",
    "CitedDocument",
    "Contract",
    "CreditNote",
    "DocumentReference",
    "Invoice",
    "Keyword",
    "LineItem",
    "Migration",
    "Money",
    "Party",
    "PurchaseOrder",
    "Receipt",
    "ReceiptItem",
    "SchemaError",
    "SchemaInfo",
    "SchemaSpec",
    "TaxIdentifier",
    "ValidationContext",
    "Validator",
    "Waybill",
    "WaybillItem",
    "add_validator",
    "adhoc",
    "custom_schemas",
    "for_model",
    "get_schema",
    "keywords",
    "list_schemas",
    "load_schema",
    "migrate",
    "parse_type",
    "pattern",
    "register_schema",
    "require_schema",
    "resolve",
    "unregister_schema",
]
