"""Training sentences for the TF-IDF classification tier, per built-in schema.

Deliberately paraphrased, not keyword-matched — if these used the same
words as the keyword rules (the document's own name in any language), the
TF-IDF tier would just be a slower copy of the rules tier. English plus
Spanish, German, French, Italian, Dutch and Portuguese for every type.
Custom schemas contribute their own through `SchemaSpec.examples`.
"""

CORPUS: dict[str, tuple[str, ...]] = {  # schema_id -> paraphrased sample sentences
    "invoice": [
        'Please remit payment within 30 days of the statement date to the account below.',
        'Balance owed for services rendered last month, itemized by hour and rate.',
        'Statement of charges for goods shipped on the attached purchase order.',
        'Payment terms: net 15. Late payments accrue 1.5% monthly interest.',
        'Itemized charges for consulting hours delivered in Q3, billed to your account.',
        'Remittance advice: please reference the order number when wiring funds.',
        'Outstanding balance for the delivered units, plus applicable sales tax.',
        'Kindly settle the enclosed statement before the remittance deadline.',
        'Charges this billing cycle for hosting, support, and add-on seats.',
        'This statement reflects goods delivered and is payable upon receipt.',
        'Sold to the below account; total reflects unit price times quantity shipped.',
        'Recurring subscription charge for the current billing period, auto-renewed.',
        'Le rogamos abone el importe indicado en un plazo de treinta días naturales.',
        'Detalle de los servicios prestados durante el mes, con su base imponible.',
        'Documento acreditativo de la operación comercial, sujeto al impuesto correspondiente.',
        'Importe pendiente por las mercancías entregadas, más el impuesto aplicable.',
        'Bitte überweisen Sie den ausgewiesenen Betrag innerhalb von 14 Tagen auf das unten genannte Konto.',
        'Für die erbrachten Leistungen berechnen wir Ihnen zuzüglich 19 % Umsatzsteuer folgenden Betrag.',
        'Montant à régler sous trente jours, TVA incluse, par virement sur le compte ci-dessous.',
        'Prestations effectuées au cours du mois, détaillées par heure et taux, hors taxes et TTC.',
        "Si prega di effettuare il pagamento dell'importo dovuto entro 30 giorni tramite bonifico.",
        'Imponibile, aliquota IVA e totale da corrispondere per i servizi forniti nel periodo.',
        'Gelieve het openstaande bedrag binnen 30 dagen over te maken onder vermelding van het nummer.',
        'Geleverde diensten van deze maand, exclusief en inclusief btw, te betalen per overschrijving.',
        'Solicitamos o pagamento do valor em dívida no prazo de 30 dias por transferência bancária.',
        'Serviços prestados no período, com base tributável, taxa de IVA e total a pagar.',
    ],
    "receipt": [
        "Here's your copy of today's purchase, keep it in case you need to return anything.",
        'Card ending 4477 approved. Have a nice day!',
        'Two items scanned at the register, change given in cash.',
        'Your order was rung up at the counter and paid for on the spot.',
        'Loyalty points earned on this visit will post to your account within 24 hours.',
        'Transaction approved — signature not required for purchases under the limit.',
        'Sale completed at register 3, cashier badge #12, till closed at close of shift.',
        "Everything scanned fine, here's what you paid and how much change you got back.",
        'In-store purchase, tax included, paid by contactless card at checkout.',
        'Print this slip for your records; returns accepted within 14 days with it.',
        'Groceries rung up one by one, coupon applied at the end before tender.',
        'Drive-thru order completed, total charged to the card on file.',
        'Justificante de la compra realizada hoy en el establecimiento, conserve este papel.',
        'Operación autorizada con tarjeta, no se requiere firma para este importe.',
        'Artículos pasados por caja y abonados en el momento, con el cambio entregado.',
        'Comprobante de la venta efectuada en el punto de venta, impuesto incluido.',
        'Vielen Dank für Ihren Einkauf. Gegeben bar, Rückgeld 3,20 EUR, MwSt. enthalten.',
        'Kartenzahlung erfolgreich, bitte Beleg für Umtausch aufbewahren.',
        'Merci de votre visite. Payé par carte sans contact, rendu monnaie en espèces.',
        'Achat réglé en caisse, articles scannés un par un, TVA comprise.',
        "Grazie per l'acquisto. Pagamento contanti, resto consegnato al cliente.",
        'Documento commerciale di vendita, pagato con carta al punto cassa.',
        'Bedankt voor uw aankoop. Betaald met pin, wisselgeld teruggegeven.',
        'Artikelen afgerekend aan de kassa, bewaar dit bewijs voor ruilen.',
        'Obrigado pela sua compra. Pago em numerário, troco entregue ao cliente.',
        'Compra paga no balcão com cartão, IVA incluído no preço.',
    ],
    "contract": [
        'Both signatories bind their respective organizations to the terms set out herein.',
        "Either side may terminate this arrangement with 60 days' written notice.",
        'This document sets out the mutual obligations of the two undersigned entities.',
        'Confidential information disclosed under this arrangement may not be shared with third parties.',
        'The undersigned entities agree to the terms and conditions set forth below.',
        'Disputes arising under this arrangement shall be resolved by binding arbitration.',
        'This instrument shall remain in force until superseded by a later signed version.',
        'Each signatory represents that it has full authority to enter into this arrangement.',
        'Upon breach, the non-breaching entity may pursue remedies available at law.',
        'This document is binding upon the successors and assigns of both entities.',
        'Renewal of this arrangement requires written consent from both signatories.',
        'Nothing herein shall be construed as creating a partnership between the entities.',
        'Ambas entidades firmantes quedan obligadas por lo estipulado en el presente documento.',
        'Cualquiera de las partes podrá resolverlo mediante preaviso por escrito.',
        'La información confidencial revelada no podrá comunicarse a terceros ajenos.',
        'Las controversias se resolverán conforme a la legislación vigente aplicable.',
        'Die unterzeichnenden Parteien verpflichten sich zur Einhaltung der nachstehenden Bestimmungen.',
        'Die Kündigung ist mit einer Frist von drei Monaten zum Quartalsende schriftlich möglich.',
        "Les parties soussignées s'engagent à respecter les conditions énoncées ci-après.",
        "Tout litige relatif à l'exécution sera soumis aux tribunaux compétents.",
        'Le parti sottoscritte si obbligano al rispetto delle clausole di seguito riportate.',
        'Il recesso può essere esercitato con preavviso scritto di sessanta giorni.',
        'De ondergetekende partijen verbinden zich tot naleving van de hierna volgende bepalingen.',
        'Geschillen worden voorgelegd aan de bevoegde rechter in het arrondissement.',
        'As partes signatárias obrigam-se ao cumprimento das cláusulas seguintes.',
        'Qualquer das partes pode rescindir mediante aviso prévio por escrito de sessenta dias.',
    ],
    "purchase_order": [
        'Official requisition for goods to be delivered to our warehouse facility.',
        'Please supply the items listed below at the agreed pricing schedule.',
        'Purchase order authorizing delivery of hardware components per quote.',
        'Authorized procurement order detailing item quantities, prices, and ship-to location.',
        'Orden de compra autorizada para el suministro de material según presupuesto acordado.',
        'Petición formal de aprovisionamiento con detalle de cantidades y precios unitarios.',
        'Hiermit beauftragen wir Sie mit der Lieferung der folgenden Artikel zu den vereinbarten Preisen.',
        'Bitte liefern Sie an unsere Lageranschrift und geben Sie unsere Referenz auf allen Papieren an.',
        'Veuillez nous livrer les articles suivants aux prix convenus selon votre devis.',
        "Demande d'approvisionnement : quantités, prix unitaires et adresse de livraison.",
        'Vi preghiamo di fornire i seguenti articoli ai prezzi concordati nel preventivo.',
        'Richiesta di approvvigionamento con quantità, prezzi unitari e luogo di consegna.',
        'Graag leveren wij de volgende artikelen tegen de overeengekomen prijzen, levering aan ons magazijn.',
        'Verzoek tot levering van onderstaande goederen, met aantallen en eenheidsprijzen.',
        'Pedimos o fornecimento dos artigos abaixo aos preços acordados no orçamento.',
        'Requisição de material com quantidades, preços unitários e local de entrega.',
        'Please ship the quantities below to our receiving dock by the requested date.',
        'Supplier is authorised to deliver the listed parts at the quoted unit prices.',
    ],
    "bank_statement": [
        'Monthly record of account debits and credits showing opening and closing ledger balances.',
        'Consolidated ledger of financial transactions, incoming wire transfers, and withdrawals.',
        'Account activity summary showing starting balance, daily movements, and ending funds.',
        'Official banking record of all funds transferred, fees deducted, and interest credited.',
        'Resumen de movimientos bancarios con desglose de cargos, abonos y saldo final.',
        'Registro mensual de cuenta bancaria con saldo inicial y transferencias recibidas.',
        'Alter Saldo, Gutschriften, Lastschriften und neuer Saldo für den Abrechnungszeitraum.',
        'Übersicht der Kontobewegungen mit Buchungstag, Wertstellung und Verwendungszweck.',
        'Ancien solde, opérations au crédit et au débit, et nouveau solde de la période.',
        "Détail des mouvements du compte avec date d'opération et date de valeur.",
        'Saldo iniziale, movimenti in accredito e addebito, saldo finale del periodo.',
        'Elenco delle operazioni sul conto corrente con data contabile e data valuta.',
        'Beginsaldo, bijschrijvingen, afschrijvingen en eindsaldo over de periode.',
        'Overzicht van de transacties op uw rekening met boekdatum en valutadatum.',
        'Saldo anterior, créditos, débitos e saldo final do período.',
        'Movimentos da conta à ordem com data-valor e descrição da operação.',
        'Interest credited and service fees debited to the account during the period.',
        'Card payments, direct debits and standing orders posted this month.',
    ],
    "acceptance_act": [
        'Certificate confirming that services have been rendered in full and accepted without objection.',
        'Formal act of completion confirming delivered scope of work meets technical specifications.',
        'Both parties confirm all contracted obligations have been completed with no mutual claims.',
        'Document certifying delivery of services rendered and authorising final commercial settlement.',
        'Acta de recepción de trabajos confirmando la conformidad de los servicios prestados sin reservas.',
        'Certificado de fin de obra y entrega de servicios sin reclamaciones mutuas pendientes.',
        'Der Auftraggeber bestätigt die vollständige und mangelfreie Erbringung der Leistungen.',
        'Die Leistungen wurden geprüft und ohne Vorbehalt abgenommen.',
        'Le client confirme la réalisation complète des prestations sans réserve.',
        "Les travaux ont été vérifiés et acceptés, aucune réclamation n'est formulée.",
        "Il committente dichiara che le prestazioni sono state eseguite a regola d'arte.",
        'I lavori sono stati verificati e accettati senza riserve da entrambe le parti.',
        'De opdrachtgever bevestigt dat de werkzaamheden volledig en zonder gebreken zijn uitgevoerd.',
        'Het werk is gecontroleerd en zonder voorbehoud aanvaard.',
        'O cliente confirma a execução integral dos serviços sem reservas.',
        'Os trabalhos foram verificados e aceites, sem reclamações mútuas.',
        'The customer signs off that the delivered scope matches the agreed specification.',
        'Handover confirmed; the parties have no outstanding claims against each other.',
    ],
    "waybill": [
        'Carrier consignment document detailing cargo packages, gross weight, and consignee destination.',
        'Freight transport manifest accompanying goods in transit from warehouse to delivery address.',
        'Shipping bill of lading recording package counts, gross kilograms, and truck driver sign-off.',
        'Goods dispatch documentation with transport details, consignee receipt, and net weight.',
        'Albarán de entrega y transporte de mercancías con detalle de bultos y peso bruto.',
        'Documento de porte y carta de consignación con recepción de mercancía por el destinatario.',
        'Absender, Empfänger, Frachtführer, Anzahl der Packstücke und Bruttogewicht in kg.',
        'Warenbegleitpapier für den Transport vom Lager zum Empfänger, Übernahme durch den Fahrer.',
        'Expéditeur, destinataire, transporteur, nombre de colis et poids brut.',
        "Document accompagnant la marchandise pendant le transport jusqu'au destinataire.",
        'Mittente, destinatario, vettore, numero di colli e peso lordo della merce.',
        'Documento che accompagna la merce durante il trasporto fino alla consegna.',
        'Afzender, geadresseerde, vervoerder, aantal colli en brutogewicht.',
        'Begeleidend document voor het goederenvervoer tot aan de ontvanger.',
        'Expedidor, destinatário, transportador, número de volumes e peso bruto.',
        'Documento que acompanha as mercadorias durante o transporte até ao destino.',
        'Pallets loaded onto the trailer, driver signature on pickup, consignee signature on delivery.',
        'Shipment of twelve cartons, gross weight 340 kg, delivered by road freight.',
    ],
    "boarding_pass": [
        'Passenger name, flight number, departure gate and seat, board no later than 30 minutes before.',
        'Gate closes 20 minutes before departure. Zone 2 boarding. Seat 14C.',
        'Present this document with your ID at security and at the gate.',
        'Operated by the partner airline. Cabin bag only. Sequence number 045.',
        'Nombre del pasajero, número de vuelo, puerta y asiento; el embarque cierra 20 minutos antes.',
        'Presente este documento junto con su documento de identidad en el control.',
        'Fluggast, Flugnummer, Flugsteig und Sitzplatz; Einstieg endet 20 Minuten vor Abflug.',
        "Passager, numéro de vol, porte et siège ; fin de l'embarquement 20 minutes avant le départ.",
        "Passeggero, numero del volo, uscita e posto; l'imbarco chiude 20 minuti prima della partenza.",
        'Passagier, vluchtnummer, gate en stoel; het instappen sluit 20 minuten voor vertrek.',
        'Passageiro, número do voo, porta e lugar; o embarque encerra 20 minutos antes da partida.',
        'Terminal 2, departure 07:45, class economy, frequent flyer number on file.',
    ],
    "credit_note": [
        'We have reduced the amount you owe us for the goods returned last week; no payment is due.',
        'This document cancels part of our earlier bill and credits the difference to your account.',
        'Correction of the previously billed quantity: the overcharge is refunded or offset against future orders.',
        'Amount credited for the damaged units, referencing the original bill of 12 March.',
        'Negative adjustment to your balance following the agreed price reduction.',
        'Se abona en su cuenta el importe de la mercancía devuelta, en referencia a la factura original.',
        'Rectificación del importe facturado anteriormente por error en el precio unitario.',
        'Wir schreiben Ihnen den Betrag für die zurückgesandte Ware gut und verrechnen ihn mit der ursprünglichen Rechnung.',
        'Korrektur der zuvor berechneten Menge, der Differenzbetrag wird erstattet.',
        "Nous créditons votre compte du montant des articles retournés, en référence à la facture d'origine.",
        'Annulation partielle de la facturation précédente suite à la remise accordée.',
        "Si accredita l'importo della merce resa, con riferimento alla fattura originale.",
        'Wij crediteren het bedrag voor de geretourneerde goederen op uw rekening.',
        'Creditamos na sua conta o valor dos artigos devolvidos, com referência à fatura original.',
    ],
    "tax_invoice": [
        'Supplier GST registration number shown; tax charged at the standard rate on taxable supplies.',
        'Total amount payable includes GST; this document serves as evidence for claiming input tax credits.',
        'Registered business number, taxable value, tax rate and tax amount for each supply.',
        'Supplies subject to goods and services tax, showing the tax-exclusive and tax-inclusive totals.',
        'Seller VAT registration, supply date and the tax amount the buyer can reclaim.',
        'Taxable supply details with the supplier ABN and the amount of GST included.',
        'Documento con el número de identificación fiscal del proveedor y la cuota tributaria repercutida.',
        'Steuernummer des leistenden Unternehmers, Leistungsdatum, Entgelt und darauf entfallender Steuerbetrag.',
        "Numéro d'identification fiscale du fournisseur, base taxable et montant de la taxe déductible.",
        "Partita IVA del cedente, base imponibile e imposta detraibile indicate separatamente.",
        'Btw-identificatienummer van de leverancier, belastbaar bedrag en in aftrek te brengen btw.',
        'Número de contribuinte do fornecedor, valor tributável e montante do imposto dedutível.',
        'GSTIN of supplier and recipient, place of supply, CGST and SGST amounts shown separately.',
        'Simplified format for supplies below the threshold under the goods and services tax act.',
    ],
    "utility_bill": [
        'Your energy use this period: previous reading, current reading and kWh consumed.',
        'Standing charge plus unit rate for the electricity supplied to the property below.',
        'Water and sewerage charges for the quarter, based on your meter readings.',
        'Monthly broadband and landline charges for the service address, including line rental.',
        'Gas consumed between the two meter readings, converted to kilowatt hours.',
        'Your supply account number, tariff name and estimated annual consumption.',
        'Consumo de energía del periodo facturado según las lecturas del contador, con el término de potencia.',
        'Ihr Verbrauch im Abrechnungszeitraum laut Zählerstand, Grundpreis und Arbeitspreis.',
        'Abschlagszahlung für Strom und Gas, Verbrauchsstelle und Zählernummer.',
        "Votre consommation d'électricité sur la période, relevé du compteur et abonnement.",
        "Consumi del periodo di fatturazione rilevati dal contatore, quota fissa e quota energia.",
        'Uw verbruik volgens de meterstanden, vastrecht en leveringskosten voor deze periode.',
        'Consumo de água no período, leituras do contador e tarifa de disponibilidade.',
        'Mobile plan charges for the billing cycle, data used and roaming.',
    ],
    "delivery_note": [
        'The goods listed below were handed over to the recipient in good condition; please sign on receipt.',
        'Items shipped against your order, quantities delivered and any items to follow on back order.',
        'Please check the delivered cartons against this list and report any shortages within 48 hours.',
        'Received the above goods in full: name, date and signature of the person accepting delivery.',
        'Contents of the consignment: article numbers, batch numbers and quantity per article.',
        'Mercancía entregada según su pedido; firme la conformidad de la recepción.',
        'Die nachstehend aufgeführte Ware wurde vollständig und unbeschädigt übergeben. Empfang bestätigt.',
        'Gelieferte Menge je Artikel, Bestellnummer und Unterschrift des Empfängers.',
        'Marchandises remises au destinataire conformément à la commande, quantités livrées ci-dessous.',
        'Merce consegnata al destinatario come da ordine, quantità e firma per ricevuta.',
        'De hieronder vermelde goederen zijn in goede staat afgeleverd; graag aftekenen voor ontvangst.',
        'Mercadorias entregues ao destinatário conforme a encomenda, com assinatura de receção.',
        'Partial shipment: remaining quantities will follow in a second delivery.',
        'Delivered to goods-in dock 3, pallets counted and signed for by the warehouse.',
    ],
    "certificate_of_origin": [
        'The undersigned authority certifies that the goods described below originate in the country stated.',
        'Goods wholly obtained or sufficiently processed in the exporting country, certified by the chamber.',
        'Exporter, consignee, means of transport, marks and numbers, description of goods and HS heading.',
        'Declaration by the exporter that the goods meet the rules of origin for preferential treatment.',
        'Stamped and signed by the issuing chamber of commerce for customs clearance at destination.',
        'La autoridad abajo firmante certifica que las mercancías descritas son originarias del país indicado.',
        'Die unterzeichnende Kammer bescheinigt, dass die nachstehend bezeichneten Waren ihren Ursprung im angegebenen Land haben.',
        "L'autorité soussignée certifie que les marchandises désignées ci-dessous sont originaires du pays indiqué.",
        "Si certifica che le merci descritte sono originarie del paese indicato, rilasciato dalla camera di commercio.",
        'De ondergetekende instantie verklaart dat de hieronder omschreven goederen van oorsprong zijn uit het vermelde land.',
        'A entidade abaixo assinada certifica que as mercadorias descritas são originárias do país indicado.',
        'Movement certificate for preferential trade, customs endorsement in box 11.',
        'Country where the goods were produced, invoice number and gross weight per package.',
        'Legalized by the consulate for export of machinery parts to the destination country.',
    ],
    "id_document": [
        'Surname, given names, date of birth, place of birth, date of issue and date of expiry of the holder.',
        'Holder signature, nationality, sex and personal number; valid for travel.',
        'Machine readable zone at the bottom of the data page with document number and check digits.',
        'Issued by the national authority; this card certifies the identity of the bearer.',
        'Licence categories, date of first issue and restrictions for the holder.',
        'Apellidos, nombre, fecha de nacimiento, nacionalidad y fecha de caducidad del titular.',
        'Name, Vornamen, Geburtsdatum, Geburtsort, Staatsangehörigkeit und gültig bis.',
        'Nom, prénoms, date et lieu de naissance, nationalité et date d’expiration du titulaire.',
        'Cognome, nome, data e luogo di nascita, cittadinanza e scadenza del documento.',
        'Naam, voornamen, geboortedatum, nationaliteit en geldig tot, afgegeven door de gemeente.',
        'Apelido, nome, data de nascimento, nacionalidade e data de validade do titular.',
        'Nazwisko, imiona, data urodzenia, obywatelstwo i data ważności dokumentu.',
        'Residence title with the type of permit, remarks and validity for the holder.',
        'Document number, issuing state and code of the bearer, photograph and signature fields.',
    ],
}
